export const environment = {
  production: true,
  instagram_token: 'INSTAGRAM_TOKEN',
  stripe_token: 'STRIPE_PUBLISHABLE_KEY',
  paypal_token: 'PAYPAL_CLIENT_ID',
  applicationUrl : {
    loginUrl:"https://stage.texvalleyb2b.in/api_web/login.php",
    loginOtpUrl:"https://stage.texvalleyb2b.in/api_web/login_otp.php",
    optVerificationUrl: "https://stage.texvalleyb2b.in/api_web/login_otp_verification.php",
    forgetPwdUrl:"https://stage.texvalleyb2b.in/api_web/forget_password.php",
    buyerSignUpUrl:"https://stage.texvalleyb2b.in/api_web/buyer_signup.php",
    buyerOtpVerificationUrl:"https://stage.texvalleyb2b.in/api_web/buyer_otp_verification.php",
    pincodeUrl:"https://stage.texvalleyb2b.in/api_web/get_pincode.php",
    getSegmentsUrl :"https://stage.texvalleyb2b.in/api_web/get_segment.php",
    searchUrl: "https://stage.texvalleyb2b.in/api_web/get_search_products.php",
    getProductListUrl: "https://stage.texvalleyb2b.in/api_web/get_product.php",
    getNewArivalsUrl: "https://stage.texvalleyb2b.in/api_web/get_new_arrival.php",
    getStateUrl : "https://stage.texvalleyb2b.in/api_web/get_state.php",
    addCartDetailsUrl : "https://stage.texvalleyb2b.in/api_web/add_cart.php",
    productDetailsUrl: "https://stage.texvalleyb2b.in/api_web/get_product_details.php",
    getOrderDetailsUrl : "https://stage.texvalleyb2b.in/api_web/get_order.php",
    getOrderCollectionDetailUrl : "https://stage.texvalleyb2b.in/api_web/get_order_items.php",
    paymentInitateUrl: "https://stage.texvalleyb2b.in/api_web/initiate_payment.php",
    deleteCartUrl : "https://stage.texvalleyb2b.in/api_web/delete_cart.php",
    confirmOrderUrl: "https://stage.texvalleyb2b.in/api_web/confirm_order.php",
    couponUrl : "https://stage.texvalleyb2b.in/api_web/update_coupon.php",
    updateProfileUrl : "https://stage.texvalleyb2b.in/api_web/send_update_profile.php",
    kycURL : "https://stage.texvalleyb2b.in/api_web/send_kyc_update.php",
    getProfileUrl : " https://stage.texvalleyb2b.in/api_web/get_profile.php",
    updateWalletUrl : "https://stage.texvalleyb2b.in/api_web/update_wallet.php"
}
};
